# https://linkerd.io/2.10/tasks/gitops/
# https://github.com/linkerd/linkerd-examples
# https://github.com/linkerd/linkerd2/blob/stable-2.11.1/charts/linkerd2/values.yaml
# https://github.com/linkerd/linkerd2/tree/main/charts
# Requires cert-manager is installed 

linkerd2:
# set to the value of the ca.crt when generating using tools/linkerd-secret.sh
# https://linkerd.io/2.11/tasks/automatically-rotating-control-plane-tls-credentials/#installing-with-helm

  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATOgAwIBAgIQfljblkm5CG9E5I1wAALRSzAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjA0MTkyMDQ3
    MThaFw0zMjA0MTYyMDQ3MThaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpbaWysNrvgd8ThPu
    FE2YD2dIPozFx7uSAO5bldWfNd2sITTrKABTk052mdFlxuzxyNMp+oB4GiDnrnGx
    /JlFLKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFC2aFJNw9eopkFXra3fsBi2H4vQdMAoGCCqGSM49BAMCA0gAMEUCIQCo
    CO0yBTYQ0AuxfkNQrtSugm+eN2+3/IwAo6AV1fwoCQIgDvhAa/NZlsKiVUYOVpbN
    bc3Aj2rgc6KJT6zML8lp5QU=
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: "kubernetes.io/tls"
  installNamespace: false

  controllerReplicas: 1