# https://linkerd.io/2.10/tasks/gitops/
# https://github.com/linkerd/linkerd-examples
# https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml

linkerd2:
  identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: "kubernetes.io/tls"
  installNamespace: false