apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB3ldMCx4KL6tNDqGXVj78USLBEecAAGFM9E+vzDHXeiSwzXyzvfOoqIYVVTktez141M+Ob+KXNBO5hmBZqz/58A5Jd+fAeL9NukKYfex2MDWnucMgLxYEGMdvJryTBrLWReZtqLOVDzd6CibU15NzZCoDvkwzJZGCexorXaqRiDqOC5KZSiGqsWNKaIOgV09EdD/01pA3cUNr3znoQdcmMU4SLLVb3KbpdsJpghsnBRS5PXxYSdVKqZd6fXp+6a3JkGTT4NFYTQf0t5TBRFLTY4v5o2eSyGKiNrAHNFY3oWGoAxD+VLLt5FFdwTkV93APZTtE1R/U6QJfp0xhOcvRG9A4cyYigUnLJc6KuajcgJW93gTqxRAEb7EnAMsDCc/t3tHdpxGygqHgPL/lAxLXZ1q5oSsXtaxGpGdBysmqIcSIACD89euF3iDED5KE3VH3mpKKDlkS1bu4bWNXL8f+aGQKzX70iOKlsbdhGzn0Xgiz/+1AQ1Xo8tw8P1WCLP8JHpS4qezNV3yolYi6DUNyjDZaFJaBRuIQ+EJJ4Qg8LJzvE8njARjZ5Ukf+EdgW/kQZVfK/49Jz/uFCS1EIxUJk/8y9BYjg+4WXKiwS7h707pHrDFPPuy6dvKiS3RKmO8IBGoV6opcwVuxAQFSLBxOq2zC9DF9jJQa70pdae1zG1VoqovLse9GrwJpq9LbSx4cM+dJA9o0/jFwi4e0EOkZJLE9TB9cx59wQgUr1PwZpWviyI4TVtwjMI0BHRGjcsPx2GA+UP2ctcSVXYknDQLg54T8m3h7tWGzJBxTWocoPEOvGavljbe0k6l9PKLhDDDB/ycuAOdXUMMM+1IeBFg6AKPlAgjBdvEM8jsXZ27GIzZ/1I7W9OuEOV39CEw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows