
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 8080
        targetPort: 8080
  webhook:
    demo-build-webhook:
      port: "8080"
      endpoint: /demo-build-webhook
      method: POST