apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
  name: demo-build-webhook
  namespace: argo
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: demo-build-webhook
                port:
                  number: 8080
            path: /demo-build-webhook
            pathType: Prefix