---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: webhook
    eventName: demo-build-webhook
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: payload-
              labels:
                app: payload
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the message you sent me:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.message
            dest: spec.containers.0.args.1

---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ci-pipeline
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: webhook
    eventName: demo-build-webhook
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: gitops-demo-workflow-
              namespace: workflows
            spec:
              entrypoint: build-ci
              serviceAccountName: argo-workflow
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              templates:
              - name: build-ci
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: container-image
                      template: build-kaniko-git-test
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: repo_url
                        value: ""
                      - name: repo_ref
                        value: ""
                      - name: repo_commit_id
                        value: ""
                      - name: container_image
                        value: davidwmcneill/
                      - name: container_tag
                        value: ""
        parameters:
        - src:
            dependencyName: github
            dataKey: body.repository.git_url
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
        - src:
            dependencyName: github
            dataKey: body.ref
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
        - src:
            dependencyName: github
            dataKey: body.repository.name
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
          operation: append
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.repository.name
          dest: spec.templates.0.dag.tasks.1.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.1.arguments.parameters.5.value
        - src:
            dependencyName: github
            dataKey: body.repository.name
          dest: spec.templates.0.dag.tasks.2.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.2.arguments.parameters.5.value
