# https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/values.yaml

argo-events:
  additionalSaNamespaces:
    - workflows
  additionalServiceAccountRules:
  - apiGroups:
      - apiextensions.k8s.io
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - customresourcedefinitions
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  singleNamespace: false