envName: env2

default:
  app:
    destination:
      server: https://kubernetes.default.svc
    source:
      targetRevision: master
    enableAutoSync: false
    autoSyncPrune: false
    autoSyncSelfHeal: false

applications:
  argo-workflows:
    enabled: false
    enableAutoSync: false