envName: local

default:
  app:
    destination:
      server: https://kubernetes.default.svc
    source:
      targetRevision: local
    enableAutoSync: false
    autoSyncPrune: false
    autoSyncSelfHeal: false

applications:
  ingress-nginx:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    autoSyncSelfHeal: true

  argo-workflows:
    enabled: true