envName: local

default:
  app:
    destination:
      server: https://kubernetes.default.svc
    source:
      targetRevision: local
    enableAutoSync: false
    autoSyncPrune: false
    autoSyncSelfHeal: false

applications:
  ingress-nginx:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    autoSyncSelfHeal: true

  argo-workflows:
    enabled: true

  argo-events:
    enabled: true

  argo-rollouts:
    enabled: true

  sealed-secrets:
    enabled: true

  kube-prometheus-stack:
    enabled: true
    # Auto sync need for nginx dependency
    enableAutoSync: true
    autoSyncPrune: true
    autoSyncSelfHeal: true

  argo-image-updater:
    enabled: true
    source:
      path: helm/cluster/argo-image-updater/overlays/local

  linkerd:
    enabled: true 

  linkerd-viz:
    enabled: true

  cert-manager:
    enabled: true 

  selenium-grid:
    enabled: true
    source:
      path: helm/cluster/selenium-grid/overlays/local
#--------------------------------------------------------------
# STACK APPLICATIONS
#--------------------------------------------------------------

  gitops-hugo:
    enabled: true

  gitops-hugo-bg:
    enabled: true  