envName: local

default:
  app:
    destination:
      server: https://kubernetes.default.svc
    source:
      targetRevision: local
    enableAutoSync: false
    autoSyncPrune: false
    autoSyncSelfHeal: false

applications:
  argo-workflows:
    enabled: true