#--------------------------------------------------------------
# DEFAULT APP OF APP VALUES
#--------------------------------------------------------------
envName: null
projectOverride: null
default:
  app:
    annotations: {}
    enableFinalizer: null
    enableAutoSync: null
    autoSyncPrune: null
    autoSyncSelfHeal: null
    syncOptions: |
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
    kustomize: null
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: null
      repoURL: https://github.com/davidwmcneill/gitops-playground-apps.git
      targetRevision: HEAD
      extraHelmFields: |
        valueFiles:
          - envValues/{{ $.Values.envName }}.yaml
    ignoreDifferences: null
#--------------------------------------------------------------
# CLUSTER APPLICATIONS
#--------------------------------------------------------------
applications:
  argo-workflows:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-workflows

  ingress-nginx:
    enabled: false
    destination:
      namespace: ingress
    project: playground-project
    source:
      path: helm/cluster/ingress-nginx

  sealed-secrets:
    enabled: false
    destination:
      namespace: kube-system
    project: playground-project
    source:
      path: helm/cluster/sealed-secrets

  argo-events:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-events

  argo-rollouts:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-rollouts
    ignoreDifferences: |
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /spec/preserveUnknownFields
          kind: CustomResourceDefinition

  kube-prometheus-stack:
    enabled: false
    destination:
      namespace: monitoring
    project: playground-project
    source:
      path: helm/cluster/kube-prometheus-stack

  argo-image-updater:
    enabled: false
    kustomize: true
    destination:
      namespace: argocd
    project: playground-project
    source:
      path: helm/cluster/argo-image-updater

  linkerd:
    enabled: false
    destination:
      namespace: linkerd
    project: playground-project
    source:
      path: helm/cluster/linkerd
    ignoreDifferences: |
      ignoreDifferences:
        - group: ""
          kind: Secret
          name:  linkerd-proxy-injector-tls
          jsonPointers:
          - /data/crt.pem
          - /data/key.pem
        - group: ""
          kind: Secret
          name:  linkerd-sp-validator-tls
          jsonPointers:
          - /data/crt.pem
          - /data/key.pem
        - group: ""
          kind: Secret
          name:  linkerd-tap-tls
          jsonPointers:
          - /data/crt.pem
          - /data/key.pem
        - group: admissionregistration.k8s.io/v1beta1
          kind: MutatingWebhookConfiguration
          name:  linkerd-proxy-injector-webhook-config
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
        - group: admissionregistration.k8s.io/v1beta1
          kind: ValidatingWebhookConfiguration
          name:  linkerd-sp-validator-webhook-config
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
        - group: apiregistration.k8s.io/v1
          kind: APIService
          name: v1alpha1.tap.linkerd.io
          jsonPointers:
          - /spec/caBundle

  linkerd-viz:
    enabled: false
    destination:
      namespace: linkerd-viz
    project: playground-project
    source:
      path: helm/cluster/linkerd-viz

  cert-manager:
    enabled: false
    destination:
      namespace: cert-manager
    project: playground-project
    source:
      path: helm/cluster/cert-manager
      extraHelmFields: |
        valueFiles:
          - envValues/{{ $.Values.envName }}.yaml

  selenium-grid:
    enabled: false
    kustomize: true
    destination:
      namespace: argocd
    project: playground-project
    source:
      path: helm/cluster/selenium-grid

#--------------------------------------------------------------
# STACK APPLICATIONS
#--------------------------------------------------------------

  gitops-hugo:
    enabled: false
    annotations:
      argocd-image-updater.argoproj.io/image-list: davidwmcneill/gitops-hugo
      argocd-image-updater.argoproj.io/write-back-method: argocd
      argocd-image-updater.argoproj.io/image-list: myapp=davidwmcneill/gitops-hugo
      argocd-image-updater.argoproj.io/myapp.update-strategy: latest
    destination:
      namespace: app-frontend
    project: playground-project
    source:
      path: helm/stack/gitops-hugo