#--------------------------------------------------------------
# DEFAULT APP OF APP VALUES
#--------------------------------------------------------------
envName: null
projectOverride: null
default:
  app:
    enableFinalizer: null
    enableAutoSync: null
    autoSyncPrune: null
    autoSyncSelfHeal: null
    syncOptions: |
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
    kustomize: null
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: null
      repoURL: https://github.com/davidwmcneill/gitops-playground-apps.git
      targetRevision: HEAD
      extraHelmFields: |
        valueFiles:
          - envValues/{{ $.Values.envName }}.yaml
    ignoreDifferences: null
#--------------------------------------------------------------
# INFRA APPLICATIONS
#--------------------------------------------------------------
applications:
  argo-workflows:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-workflows

  ingress-nginx:
    enabled: false
    destination:
      namespace: ingress
    project: playground-project
    source:
      path: helm/cluster/ingress-nginx

  sealed-secrets:
    enabled: false
    destination:
      namespace: kube-system
    project: playground-project
    source:
      path: helm/cluster/sealed-secrets

  argo-events:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-events

  argo-rollouts:
    enabled: false
    destination:
      namespace: argo
    project: playground-project
    source:
      path: helm/cluster/argo-rollouts