# https://github.com/argoproj/argo-helm/blob/master/charts/argo-rollouts/values.yaml

argo-rollouts:
  dashboard:
    enabled: true
  apiVersionOverrides:
    # -- String to override apiVersion of ingresses rendered by this helm chart
    ingress: "networking.k8s.io/v1"
