# https://github.com/argoproj/argo-helm/blob/master/charts/argo-rollouts/values.yaml

argo-rollouts:
  dashboard:
    enabled: true
  # apiVersionOverrides:
  #   # -- String to override apiVersion of ingresses rendered by this helm chart
  #   ingress: "networking.k8s.io/v1"

  controller:
    # -- Value of label `app.kubernetes.io/component`
    component: rollouts-controller
    # -- [Node selector]
    nodeSelector: {}
    # -- [Tolerations] for use with node taints
    tolerations: []
    # -- Assign custom [affinity] rules to the deployment
    affinity: {}
    # -- The number of controller pods to run
    replicas: 1
    image:
      # -- Registry to use
      registry: quay.io
      # -- Repository to use
      repository: argoproj/argo-rollouts
      # -- Overrides the image tag (default is the chart appVersion)
      tag: "latest"