apiVersion: v2
name: kube-prometheus-stack
version: 0.1.0

# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml

dependencies:
- name: kube-prometheus-stack
  version: 58.5.3
  repository: https://prometheus-community.github.io/helm-charts