# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

kube-prometheus-stack:
  grafana:
    enabled: true
    namespaceOverride: ""

    ## ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
    ##
    forceDeployDatasources: false

    ## ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
    ##
    forceDeployDashboards: false

    ## Deploy default dashboards.
    ##
    defaultDashboardsEnabled: true

    adminPassword: prom-operator

    ingress:
      enabled: true

      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      labels: {}
      hosts: []
      path: /grafana
      tls: []


  prometheus:
    ingress:
      enabled: true
      annotations: {}
      labels: {}
      hosts: []

      ## Paths to use for ingress rules - one path should match the prometheusSpec.routePrefix
      ##
      paths: 
      - /prom

      tls: []

    prometheusSpec:
      routePrefix: /prom