# https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/values.yaml

metrics-server:
# TODO: migrate to ecr
  image:
    registry: docker.io
    repository: bitnami/metrics-server
    tag: 0.4.1-debian-10-r0
  extraArgs:
    kubelet-insecure-tls: true

  apiService:
    ## Specifies whether the v1beta1.metrics.k8s.io API service should be created
    ## This should not be necessary in k8s version >= 1.8
    ##
    create: true

  hostNetwork: true