{{- $fullName := include "fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
            path: /gitops-hugo
            pathType: Prefix